# Generated by Django 5.0.3 on 2024-04-24 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Class', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=50)),
                ('Class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ContentKL.classes')),
            ],
        ),
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Topic', models.CharField(max_length=300)),
                ('Class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ContentKL.classes')),
                ('Subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ContentKL.subjects')),
            ],
        ),
        migrations.CreateModel(
            name='subtopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('overview', models.TextField()),
                ('videolink', models.CharField(max_length=500)),
                ('Class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ContentKL.classes')),
                ('Subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ContentKL.subjects')),
                ('Topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ContentKL.topics')),
            ],
        ),
    ]
