# Generated by Django 5.0.3 on 2024-05-09 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContentKL', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('Subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ContentKL.subjects')),
            ],
        ),
    ]
