# Generated by Django 5.0.3 on 2024-05-09 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContentKL', '0002_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=300)),
                ('Subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ContentKL.subjects')),
            ],
        ),
        migrations.DeleteModel(
            name='images',
        ),
    ]
