# Generated by Django 5.0.3 on 2024-06-17 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContentKL', '0003_image_delete_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='Class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ContentKL.classes'),
        ),
    ]
